# Netlify build configuration for ReelApps Monorepo

[build]
  # This command is run to build the site. Using build:netlify to skip linting.
  command = "pnpm build:netlify"
  
  # This is the directory that Netlify will deploy. 
  # It should contain the main app's build output.
  publish = "apps/home/dist"
  
  # The directory where pnpm-lock.yaml is located.
  # This is the root of the monorepo.
  base = "/"

[build.environment]
  # Set the pnpm version to ensure consistency.
  PNPM_VERSION = "9.1.0"
  
  # Set the Node.js version.
  NODE_VERSION = "18"

# Domain-specific redirects to serve different apps
[[redirects]]
  from = "https://www.reelcv.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelcv&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://reelcv.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelcv&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.reelpersona.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelpersona&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://reelpersona.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelpersona&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.reelhunter.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelhunter&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://reelhunter.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelhunter&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.reelprojects.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelproject&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://reelprojects.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelproject&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.reelskills.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelskills&path=:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://reelskills.co.za/*"
  to = "https://www.reelapps.co.za/?app=reelskills&path=:splat"
  status = 200
  force = true

# Redirects and rewrites for a Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 