# Netlify build configuration for ReelApps Monorepo

[build]
  # This command is run to build the site. It now includes our full CI test and validation script.
  command = "pnpm ci:test && pnpm build"
  
  # This is the directory that Netlify will deploy. 
  # It should contain the main app's build output.
  publish = "apps/home/dist"
  
  # The directory where pnpm-lock.yaml is located.
  # This is the root of the monorepo.
  base = "/"

[build.environment]
  # Set the pnpm version to ensure consistency.
  PNPM_VERSION = "9.1.0"
  
  # Set the Node.js version.
  NODE_VERSION = "18"

# Redirects and rewrites for a Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 